name: Test, Build & Release

on:
  - push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build
        run: rm -rf lib/ && npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: DEVan BOTomly
          GIT_AUTHOR_EMAIL: dev.bot@parcellab.com
          GIT_COMMITTER_NAME: DEVan BOTomly
          GIT_COMMITTER_EMAIL: dev.bot@parcellab.com
        run: npx semantic-release
