name: Test, Build & Release

on:
  - push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build
        run: rm -rf lib/ && npm run build

#      - uses: actions/create-github-app-token@v1
#        id: app-token
#        with:
#          app-id: ${{ secrets.PARCELLAB_BOT_APPID }}
#          private-key: ${{ secrets.PARCELLAB_BOT_KEY }}

      - run: git config user.email "dev.bot@parcellab.com"
      - run: git config user.name "parcellab-dev-bot"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git config user.name "parcellab-dev-bot"
          git config user.email "dev.bot@parcellab.com"          
          npx semantic-release
