name: Test, Build & Release
on:
  push:
    branches:
      - master
    paths:
      - "**.js"
      - "**.ts"
      - Containerfile
      - package.json
  pull_request:
    paths:
      - "**.js"
      - "**.ts"
      - package.json
  workflow_dispatch:
jobs:
  verify:
    uses: parcelLab/ci/.github/workflows/js.yaml@v1
    secrets:
      npmGithubReadToken: ${{ secrets.PACKAGES_READ_TOKEN }}
  draft:
    if: github.ref == 'refs/heads/master'
    needs:
      - verify
    uses: parcelLab/ci/.github/workflows/release.yaml@v1
    with:
      targetBranch: master
    secrets:
      repoAccessToken: ${{ secrets.REPO_ACCESS_TOKEN_OPEN_SOURCE }}
